CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR2(200) NOT NULL,
    email       VARCHAR2(320),

    CONSTRAINT pk_customer
        PRIMARY KEY (customer_id)
);